#import "../CoreExperiencePart.gql"
#import "../guide/one.gql"

fragment Slot on Slot {
  start
  end
  guide {
    ...GuideResponse
  }
  experience {
    data {
      id
      attributes {
        ...CoreExperiencePart
      }
    }
  }
}
