#import "./slot/one.gql"

fragment BookingPart on BookingRelationResponseCollection {
  data {
    id
    attributes {
      size
      types {
        ...ExperienceTypePart
      }
      experience_slot {
        ...Slot
      }
    }
  }
}
