#import "../fragments/ExternalExperienceSlot.gql"
fragment BookingPart on BookingRelationResponseCollection {
  data {
    id
    attributes {
      size
      types {
        ...ExperienceTypePart
      }
      experience_slot {
        ...ExperienceSlotPart
      }
    }
  }
}
