fragment CoreExperiencePart on Experience {
  title
  duration
  price
  transportation
  description
  stars
  groupSize
  handifriendly
  location
  amountPerAge {
    baby {
      id
      amount
    }
    adult {
      id
      amount
    }
    teenager {
      id
      amount
    }
    children {
      id
      amount
    }
  }
  discountPerGroupSize {
    id
    discount
    min
    max
  }
  thresholds {
    id
    groupSizeMin
    groupSizeMax
  }
  photos {
    data {
      attributes {
        formats
      }
    }
  }
}
