#import "./CoreExperiencePart.gql"
#import "./GuideProfile.gql"

fragment CoreUser on UsersPermissionsUser {
  location
  firstname
  lastname
  email
  phone
  location
  favorite {
    experiences {
      data {
        id
        attributes {
          ...CoreExperiencePart
        }
      }
    }
    guides {
      data {
        id
        attributes {
          ...GuideProfile
        }
      }
    }
  }
  picture {
    data {
      attributes {
        formats
      }
    }
  }
}
