#import "./AbstractGuidePart.gql"
fragment ExperienceSlotPart on ExperienceSlotEntityResponse {
  data {
    id
    attributes {
      start
      end
      guide {
        ...AbstractGuidePart
      }
      experience {
        data {
          id
        }
      }
    }
  }
}
