#import "./CoreExperiencePart.gql"

fragment ExperienceSlotPart on ExperienceSlotEntity {
  id
  attributes {
    start
    end
    experience {
      data {
        id
        attributes {
          ...CoreExperiencePart
        }
      }
    }
  }
}
