fragment FavoritePlace on FavoritePlaceEntityResponse {
  data {
    id
    attributes {
      title
      description
      picture {
        data {
          id
          attributes {
            previewUrl
            formats
          }
        }
      }
    }
  }
}
