#import "./ExternalUser.gql"
#import "./ThemePart.gql"
#import "./LanguagePart.gql"
#import "./CoreExperiencePart.gql"
#import "./ExperienceTypePart.gql"
#import "./guide/one.gql"
#import "./slot/all.gql"

fragment FullExperience on ExperienceEntityResponse {
  data {
    id
    attributes {
      ...CoreExperiencePart
      themes {
        ...ThemePart
      }
      languages {
        ...LanguagePart
      }
      types {
        ...ExperienceTypePart
      }
      guide {
        ...GuideResponse
      }
      slots {
        ...SlotsResponse
      }
    }
  }
}
