query experience($id: ID!) {
  experience(id: $id) {
    data {
      attributes {
        title
        duration
        price
        transportation
        description
        stars
        groupSize
        handifriendly
        location
        themes {
          data {
            attributes {
              name
            }
          }
        }
        languages {
          data {
            attributes {
              value
            }
          }
        }
        photos {
          data {
            attributes {
              previewUrl
              url
            }
          }
        }
      }
    }
  }
}
