#import "../fragments/ThemePart.gql"
#import "../fragments/LanguagePart.gql"
#import "../fragments/CoreExperiencePart.gql"

query {
  experiences {
    data {
      id
      attributes {
        ...CoreExperiencePart
        themes {
          ...ThemePart
        }
        languages {
          ...LanguagePart
        }
      }
    }
  }
}
