#import "../fragments/ThemePart.gql"
#import "../fragments/LanguagePart.gql"
#import "../fragments/CoreExperiencePart.gql"
#import "../fragments/ExperienceTypePart.gql"

query filterExperiences($guideID: ID!){
  experiences (filters: {
    guide: {
      id: {
        eq: $guideID
      }
    }
  }){
    data {
      id
      attributes {
        ...CoreExperiencePart
        themes {
          ...ThemePart
        }
        languages {
          ...LanguagePart
        }
        types {
          ...ExperienceTypePart
        }
      }
    }
  }
}
