fragment ExperiencePart on ExperienceEntityResponse {
  data {
    id
    attributes {
      title
    }
  }
}

query experienceSlot($id: ID!) {
  experienceSlot(id: $id) {
    data {
      id
      attributes {
        experience {
          ...ExperiencePart
        }
      }
    }
  }
}
