#import "../fragments/ThemePart.gql"
#import "../fragments/LanguagePart.gql"
#import "../fragments/CoreExperiencePart.gql"
#import "../fragments/PhotoPart.gql"

query experience($id: ID!) {
  experience(id: $id) {
    data {
      id
      attributes {
        ...CoreExperiencePart
        photos {
          ...PhotoPart
        }
        themes {
          ...ThemePart
        }
        languages {
          ...LanguagePart
        }
      }
    }
  }
}
