query {
  experiences {
    data {
      id
      attributes {
        title
        duration
        price
        transportation
        description
        stars
        handifriendly
        groupSize
        themes {
          data {
            attributes {
              name
            }
          }
        }
        languages {
          data {
            attributes {
              value
            }
          }
        }
      }
    }
  }
}
