query guide($id: ID!) {
  guide(id: $id) {
    data {
      id
      attributes {
        experience_slots {
          data {
            id
            attributes {
              start
              end
            }
          }
        }
        experiences {
          data {
            id
          }
        }
      }
    }
  }
}
