query ExampleQuery {
  guides {
    data {
      attributes {
        location
        user {
          data {
            attributes {
              firstname
              lastname
              picture {
                data {
                  attributes {
                    formats
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
