#import "../fragments/CoreExperiencePart.gql"

query guide($id: ID!) {
  guide(id: $id) {
    data {
      id
      attributes {
        background
        headline
        description
        location
        workExperiences
        specialties
        interests
        languages {
          data {
            id
            attributes {
              value
            }
          }
        }
        user {
          data {
            id
            attributes {
              firstname
              lastname
              picture {
                data {
                  attributes {
                    previewUrl
                    formats
                  }
                }
              }
            }
          }
        }
        favorite_place {
          data {
            id
            attributes {
              picture {
                data {
                  attributes {
                    previewUrl
                    formats
                  }
                }
              }
              title
              description
            }
          }
        }
        experiences {
          data {
            id
            attributes {
              ...CoreExperiencePart
              photos {
                data {
                  id
                  attributes {
                    previewUrl
                    formats
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
