#import "../fragments/CoreExperiencePart.gql"
#import "../fragments/ExperienceSlotPart.gql"

query guide($id: ID!) {
  guide(id: $id) {
    data {
      id
      attributes {
        experience_slots {
          data {
            ...ExperienceSlotPart
          }
        }
        experiences {
          data {
            id
            attributes {
              ...CoreExperiencePart
            }
          }
        }
      }
    }
  }
}
