#import "../fragments/CoreExperiencePart.gql"
#import "../fragments/ExperienceSlotPart.gql"

query {
  me {
    id
    socketID
    friends {
      data {
        id
        attributes {
          username
          socketID
        }
      }
    }
    guide {
      data {
        id
        attributes {
          experience_slots {
            data {
              ...ExperienceSlotPart
            }
          }
          experiences {
            data {
              id
              attributes {
                ...CoreExperiencePart
              }
            }
          }
        }
      }
    }
  }
}
