#import "../../../fragments/CoreGuidePart.gql"
#import "../../../fragments/CoreUser.gql"

query guideAccount($id: ID!) {
  usersPermissionsUser(id: $id) {
    data {
      id
      attributes {
        ...CoreUser
        guide {
          ...CoreGuidePart
        }
      }
    }
  }
}
