#import "../../../fragments/CoreExperiencePart.gql"

query usersPermissionsUser($id: ID!) {
  usersPermissionsUser(id: $id) {
    data {
      id
      attributes {
        picture {
          data {
            attributes {
              previewUrl
              formats
            }
          }
        }
        location
        firstname
        lastname
        email
        phone
        location
        guide {
          data {
            id
            attributes {
              user {
                data {
                  id
                  attributes {
                    firstname
                    lastname
                    picture {
                      data {
                        attributes {
                          previewUrl
                          formats
                        }
                      }
                    }
                  }
                }
              }
              location
              headline
              description
              background
              workExperiences
              specialties
              interests
              favorite_place {
                data {
                  id
                  attributes {
                    title
                    description
                  }
                }
              }
              languages {
                data {
                  id
                  attributes {
                    value
                  }
                }
              }
              experiences {
                data {
                  id
                  attributes {
                    ...CoreExperiencePart
                  }
                }
              }
              experienceSlots {
                data {
                  id
                  attributes {
                    experience {
                      data {
                        id
                        attributes {
                          title
                        }
                      }
                    }
                    start
                    end
                    bookings {
                      data {
                        id
                        attributes {
                          size
                          user {
                            data {
                              id
                              attributes {
                                username
                                email
                                phone
                                firstname
                                lastname
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
