#import "../../../fragments/bookingExperience.gql"
#import "../../../fragments/ExperienceSlotPart.gql"
#import "../../../fragments/CoreUser.gql"

query user($id: ID!) {
  usersPermissionsUser(id: $id) {
    data {
      id
      attributes {
        ...CoreUser
        bookings {
          data {
            id
            attributes {
              size
              experience_slot {
                ...ExperienceSlotPart
              }
              experience {
                ...BookingExperience
              }
            }
          }
        }
      }
    }
  }
}
